name: CoordinatesCommandPlugin
version: 1.0.0
main: com.ethanphunter.coordinatescommand.CoordinatesCommandPlugin
description: A plugin that adds a command to post current coordinates in chat
author: Ethan Hunter
api-version: '1.20'
commands:
  coordinates:
    description: "Posts the players current coordinates in chat"
    usage: "/coordinates <args>"
    aliases: [coord, coords]